### ISSUE TITLE
V2.0.3 Release Checklist

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#134]
- [x] Power base expanders.
- [x] Inventory base expanders.
- [x] Camouflagable turret bases.
- [x] Owner breakable electric fences.
- [x] Owner breakable walls.
- [x] Some texture updates
- [x] Recycler addon

**Comment by Poenjabiesous** [comment]
V2.0.3 Done.

**Comment by Keridos** [comment]
A small note: this should be 2.1.0 because the last number is normally bugfixes only, features are either the second or first number.

**Comment by Poenjabiesous** [comment]
I was hoping to use this release as the precursor to 2.1.0, but you make a good point. I guess we can do that.
